{% set name = "nest-simulator" %}
{% set version = "3.8" %}
{% set build = 2 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nest/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: eb255f8828be001abea0cddad2f14d78b70857fc82bece724551f27c698318c8

build:
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or py<38 or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - make
    - cmake
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - cython
    - gsl >=1.11
    - hdf5
    - h5py
    - libboost-headers
    - libcblas
    - liblapack
    - libtool
    - ncurses
    - python
    - readline
    - scipy
    - openssh
    - statsmodels
    - zlib
  run:
    - cmake
    - gsl
    - hdf5
    - h5py
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - libtool
    - openmpi
    - python
    - python.app  # [osx]
    - python_abi
    - readline
    - scipy
    - statsmodels

test:
  requires:
    - pytest
    - pytest-timeout
    - pytest-xdist
    - pytest-pylint
    - pytest-mypy
    - pytest-cov
    - numpy
    - pandas
    - scipy
    - mpi4py
    - data-science-types
    - h5py
    - terminaltables
    - pycodestyle
    - pydocstyle
    - rstcheck
    - mypy >=0.8
    - cppcheck
  imports:
    - nest
  commands:
    - nest --help
    - sli --help

about:
  home: http://www.nest-simulator.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: |
    NEST is a simulator for spiking neural network models that focuses on the dynamics, size and structure of neural
    systems rather than on the exact morphology of individual neurons.
  description: |
    You can use NEST either as a for the interpreted programming language Python (PyNEST) or as a stand alone
    application (nest). PyNEST provides a set of commands to the Python interpreter which give you access to NEST's
    simulation kernel. With these commands, you describe and run your network simulation. You can also complement
    PyNEST with PyNN, a simulator-independent set of Python commands to formulate and run neural simulations. While
    you define your simulations in Python, the actual simulation is executed within NEST's highly optimized
    simulation kernel which is written in C++. A NEST simulation tries to follow the logic of an
    electrophysiological experiment that takes place inside a computer with the difference, that the neural system
    to be investigated must be defined by the experimenter. The neural system is defined by a possibly large number
    of neurons and their connections. In a NEST network, different neuron and synapse models can coexist. Any two
    neurons can have multiple connections with different properties. Thus, the connectivity can in general not
    be described by a weight or connectivity matrix but rather as an adjacency list. To manipulate or observe the
    network dynamics, the experimenter can define so-called devices which represent the various instruments (for
    measuring and stimulation) found in an experiment. These devices write their data either to memory or to file.
    NEST is extensible and new models for neurons, synapses, and devices can be added. To get started with NEST,
    please see the documentation page <https://nest-simulator.org/documentation/>.
  doc_url: https://nest-simulator.readthedocs.io/en/latest/
  dev_url: https://github.com/nest/nest-simulator

extra:
  recipe-maintainers:
    - steffengraber
