{% set name = "nesttest" %}
{% set version = "fixmacosjupyter" %}

{% set build = 2 %}

# mpi must be defined for conda-smithy lint
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prefer nompi builds via a build number offset
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/steffengraber/nest-simulator/archive/{{ version }}.tar.gz
  sha256: fd4c8266350725b3a5a1785296e8418c90b225605fd6de981bbc0fa2dadf22f8

build:
  number: {{ build }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # mpi_*` for any mpi
  # nompi_*` for no mpi
  # examle see;
  # https://github.com/conda-forge/h5py-feedstock/blob/master/recipe/meta.yaml
  string: "{{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  skip: true  # [win]
  skip: true  # [py<30]
  # skip: true  # [py<30]
  osx_is_app: True

requirements:
  build:
    - cmake >=3.6
    - git
    - llvm-openmp  # [osx]
    - make
    - openmp  # [linux][mpi != 'nompi']
    - sed
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - gsl
    - {{ pin_compatible('libcblas') }}
    - libtool
    - llvm-openmp  # [osx]
    - matplotlib
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - openmp  # [linux][mpi != 'nompi']
    - python
    - readline
    - scipy
    - openssh
    - statsmodels
    - zlib
  run:
    - cython
    - gsl
    - {{ pin_compatible('libcblas') }}
    - libtool
    - llvm-openmp  # [osx]
    - matplotlib
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - openmp  # [linux][linux][mpi != 'nompi']
    - python
    - python.app  # [osx]
    - readline
    - scipy
    - statsmodels
    - openssh
    - zlib

test:
  imports:
    - nest
  commands:
    - nest --help
    - sli --help

about:
  home: http://www.nest-simulator.org/
  license:  GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: |
    NEST is a simulator for spiking neural network models that
    focuses on the dynamics, size and structure of neural systems rather than
    on the exact morphology of individual neurons.

  doc_url: https://nest-simulator.readthedocs.io/en/latest/
  dev_url: https://github.com/nest/nest-simulator

extra:
  recipe-maintainers:
    - steffengraber
