conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
conda_build:
  pkg_format: '2'
azure:
  store_build_artifacts: True
provider:
  linux_64: azure
  osx_64: azure
conda_build_tool: mambabuild

