build_platform:
  osx_arm64: osx_arm64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native
test_on_native_only: True
azure:
  store_build_artifacts: True
provider:
  linux_64: azure
  osx_64: azure
conda_build_tool: conda-build+conda-libmamba-solver
